### ISSUE TITLE
OpenERP LED display...

### ISSUE THREAD

**Issue by dattadhonde** [guerrerocarlos/OpenERP-ledDisplay#1]
can we use it for PS2 typeof port... I'm trying it with keyboard... what will be changes..

**Comment by guerrerocarlos** [comment]
The script uses the python "eventlet" module and is meant to work with any COM port used as an "output" so it will depend on how is your PS2 port identified in your system in order to make it work. 

But I dont understand how is that you want to use a keyboard with it?

**Comment by dattadhonde** [comment]
Hello Sir,

sorry to take ur time...

xmlhttp.open("GET","http://localhost:8100/"+String(line1)+"___"+String(line2),false);  // for serial port(com port)

Here we are communicating with com port number 8100, can we have PS/2 or USB port, a PS/2 or USB dont have any port number(8100 in above case) associated with them so if I have LED device with USB port then how to resolve this...? I mean what will be changes in above line to access the USB port? We have solution for this as using Virtual Com Port which converts USB to Com port but if I need to do it with using only USB ?

**Comment by guerrerocarlos** [comment]
The 8100 is not a COM port number, is a TCP/IP port number, the script is the one that creates a WSGI service in that TCP/IP port.

That WSGI service accepts any HTTP request (that can come in this case, from the in the OpenERP POS Javascript), then reads the information that comes in the URL ("line1" and "line2") and is then written into the COM1 port using the python "serial" module, as you can see in the line https://github.com/guerrerocarlos/OpenERP-ledDisplay/blob/master/pos.py#L18

If you want to write it to any other kind of port (parallel, USB or whatever) you would have to:
- Use the module you really need instead of "serial": https://github.com/guerrerocarlos/OpenERP-ledDisplay/blob/master/pos.py#L1
- Change the **init** function to initialize your port intead of the serial (COM) that the script is using right now: https://github.com/guerrerocarlos/OpenERP-ledDisplay/blob/master/pos.py#L13
- Write the data in the right way to your port:
  https://github.com/guerrerocarlos/OpenERP-ledDisplay/blob/master/pos.py#L18

**Comment by dattadhonde** [comment]
Hello Sir,
     I am trying to communicate with usb pen drive... based on vendor id & product id we can communicate with this USB device but I am not getting what to put for 8100 for path thing in pos.js...  8100 is TCP/IP port number but pen drive is on local USB port so how to identify it... 

```
           xmlhttp.open("GET","http://localhost:8100/"+String(line1)+"___"+String(line2),false); 
```

  &  same way for 8100 here in pos.py
        wsgi.server(eventlet.listen(('', 8100)), self.bridge)
        self.ser.close()

**Comment by guerrerocarlos** [comment]
I think we have a concept problem in here.

Please tell me exactly what are you trying to do, so I can help you better.

**Comment by dattadhonde** [comment]
Ok so let me tell you, I will be communicating with LED display but for now it is not available with me, I will get it few days after but till then I want to try communicate with other devices for testing purpose only, so if it works with USB ports then I can order LED Device with USB ports only and not with com ports, as USB ports are popular today and they are replacing serial com ports. I want to know whether is it possible to send message to any device like pen drive, printer or modem attached on usb port.....? Can we do that with above code...?

**Comment by dattadhonde** [comment]
Update:   Using PyUSB module I can find the USB device, write to it in appropriate way.....  

I was receiving an error in xmlhttp.send() because of-----

xmlhttp.open("GET","http://localhost:8100/"+String(line1)+"___"+String(line2),false); 

Now I have added  TCP port number 5354 and it is not giving any error

xmlhttp.open("GET","127.0.0.1/5354"+String(line1)+"___"+String(line2),false); 

Now can I set my USB pen drive on this TCP/IP port ? like they have set com port on 8100 TCP/IP port... Help me how to do this..?  Plz comment on relation between USB port and TCP/IP port...

**Comment by guerrerocarlos** [comment]
Ok, the thing is this:

The code in this repository makes a "bridge" between a TCP/IP port and a COM port, it works like this:

It opens a simple WSGI server in the port 8100, and whatever URL is requested, it takes the words written in line1 and line2 in here: "http://localhost:8100/"+String(line1)+"___"+String(line2) and sends it to the COM port as an output.]

If you want to talk to USB instead of COM, you must only change the "Sending data to COM port" part of the code and put your "Sending data to USB port" code, you dont need to change the TCP/IP por or anything else.

**Comment by datta123** [comment]
Hello Sir,
        The code given for passing the message to LED device .. is it generic code ? I mean if we write it USB port of the device by end point instance through    ep.write(" ")... will it be displayed on any kind of LED with all your libraries installed?

**Comment by guerrerocarlos** [comment]
The code given right now only works for COM port, but it could easily be adapted to work with USB devices.

**Comment by diassynthesis** [comment]
Hello Sir;
How can we use it under Linux ?

Best regards.

**Comment by guerrerocarlos** [comment]
It works on linux just like it is. No modifications need to be made.

**Comment by diassynthesis** [comment]
Thank you Sir.
but correct me if i'm wrong.
1_ sudo apt-get install python-greenlet
2_ sudo apt-get install python-eventlet
3_ For openERP 7  Add:<< function ledDisplay(line1,line2){ ...... >>  to the file addons/point_of_sale/static/src/js/point_of_sale.js
4_ Do a: python setup.py install (from within a directory containing the 3 files ServiceLauncher.py ,   pos.py, and setup.py)

5_ My question (for example), How to display the "amount_total" to be paid ?

Best regards.

**Comment by guerrerocarlos** [comment]
You have to put the "ledDisplay" function exactly in the right function in the .js files of the pos with the right variables.

On OpenERP 7, you must put the ledDisplay function definition in main.js

while the rest of the function invocations depend on exactly what do you want to show in the customer display, for example, in order to show the information of each product that the client is buying you have to add this line:

ledDisplay(product.get('name'),product.get('list_price')+" "+this.pos.get('currency').symbol);

to the function "addProduct" in models.js

It is different on OpenERP 6.1 and 7, but it just requires you to understand the way the pos works.

Remember that OpenERP's POS is based on [Backbone.js](http://backbonejs.org) so it's very usefull to undestand how backbone works.

If you need a specific implementation I can provide you with personal assistance and development service for you to achieve it in less time.

**Comment by diassynthesis** [comment]
thank you very much for your explanations.
I will probably contact you if needed.

**Comment by abenzbiria** [comment]
Hello ,

Thank you for this rich informations. In my case we need to edit french letters like : à , è,é,  how can make it ? this is a varaible in code to specify codage ? .

**Comment by guerrerocarlos** [comment]
The limitations about the letters that you can use are only imposed by the Customer Display hardware, try it out and if you have any trouble you can contact me.

**Comment by abenzbiria** [comment]
I 'll try it in comming few days with two kinds of display by POSLIGNE : OCD 150 and OCD 100 .
